stages:
  - test
  - deploy

test:
  stage: test
  tags:
    - python3-cicd
  before_script:
    - python3 -m venv .bbtest
    - . ./.bbtest/bin/activate
    - pip install ".[test]"
  script:
    - python -m pytest tests --full
  only:
    - merge_requests

mypy-check:
  stage: test
  tags:
    - python3-cicd
  before_script:
    - python3 -m venv .bbtest
    - . ./.bbtest/bin/activate
    - pip install ".[test]"
      # Workaround a mypy cache bug.
    - rm -rf .mypy_cache
  script:
    - mypy --install-types --non-interactive src/bbworker
  only:
    - merge_requests

upload:
  stage: deploy
  tags:
    - python3-cicd
  before_script:
    - python3 -m venv .build
    - . ./.build/bin/activate
    - pip install build
    - pip install twine==1.15.0
  script:
    - python -m build
    - twine upload --repository-url $PYPISERVER_URL -u $PYPISERVER_USERNAME -p $PYPISERVER_PASSWORD dist/*
  only:
    - tags
  when: manual

upload-winservice:
  stage: deploy
  tags:
    - windows
  before_script:
    - chcp 65001
    - py -3 -m venv .winservice
    - call ./.winservice/Scripts/activate
    - pip install ".[sentry,otel,winservice]"
    - pip install pyinstaller==5.7.0
    - pip install boto3==1.23.10
  script:
    - cd winservice
    - call build.bat
    - python upload.py "dist/bbworker_service.exe" "bbworker_service-latest" "--s3-key" %S3_ACCESS_KEY% "--s3-secret" %S3_ACCESS_SECRET% "--s3-bucket" "gzdev2-echoes-assets"
    - python upload.py "install.py" "bbworker_service_install.py" "--s3-key" %S3_ACCESS_KEY% "--s3-secret" %S3_ACCESS_SECRET% "--s3-bucket" "gzdev2-echoes-assets"
  only:
    - tags
  when: manual
