test:
  tags:
    - python3-cicd
  before_script:
    - python3 -m venv .bbtest
    - . ./.bbtest/bin/activate
    - pip install ".[test]"
  script:
    - python -m pytest tests
  only:
    - merge_requests

mypy-check:
  tags:
    - python3-cicd
  before_script:
    - python3 -m venv .bbtest
    - . ./.bbtest/bin/activate
    - pip install ".[test]"
      # Workaround a mypy cache bug.
    - rm -rf .mypy_cache
  script:
    - mypy worker
  only:
    - merge_requests
