buildbarn:
  cas_address: "10.212.214.130:8980"
  scheduler_address: "10.212.214.123:8983"
platform:
  properties:
    - name: "os"
      value: "windows"
worker_id:
  node: "windows-dev"
filesystem:
  cache_root: "tmp/file_cache"
build_directory_builder:
  cache_root: "tmp/dir_cache"
build_root: "tmp/build"
concurrency: 10
